development:
  adapter: postgresql
  encoding: unicode
  database: bradleyd_development
  pool: 5
  host: localhost
  username: bradleyd
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bradleyd_test
  pool: 5
  host: localhost
  username: bradleyd
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bradleyd_production
  pool: 5
  username: bradleyd
  host: localhost
  password:
