theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1_add:
  - advlink
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - advlink
plugins:
  - table
  - fullscreen
  - advlink
