default:
  plugins:
    - image
    - link
    - code
    - preview
alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | link image | undo redo | table | code
  plugins:
    - table
